esphome:
  name: esp01
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "*******"
  password: "******"
  fast_connect: true

  manual_ip:
    static_ip: 192.168.1.12
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
# logger:

# Enable Home Assistant API
api:

ota:
  
binary_sensor:
  - platform: gpio
    pin: GPIO2
    name: "Button"
