esphome:
  name: esp01
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 600
    then:
      - switch.turn_on: fakeswitch
  on_shutdown:
    then:
      - switch.turn_off: fakeswitch

deep_sleep:
  run_duration: 10s
#  sleep_duration: 10min

wifi:
  ssid: "*******"
  password: "*******"
  fast_connect: true
  power_save_mode: HIGH

  manual_ip:
    static_ip: 192.168.1.19
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
# logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: template
    name: "Switch"
    optimistic: true
    id: fakeswitch
